config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#welcome'
  
  get 'portfolio' => 'pages#portfolio'
  
  get 'about' => 'pages#about'
  
  get 'contact' => 'pages#contact'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="row">
      <div class="menu col-xs-8">
        <ul>
          <li><%= link_to "welcome", root_path %></li>
          <li><%= link_to "portfolio", portfolio_path %></li>
          <li><%= link_to "images", "http://imgur.com/a/jDquy" %></li>
          <li><%= link_to "about", about_path %></li>
          <li><%= link_to "contact", contact_path %></li>
        </ul>
      </div>
      <div class="name col-xs-4">
        <h1>jerry goldshine</h1>
      </div>
    </div>
  </div>
</div>
  
<%= yield %>

<div class="footer">
  <div class="container">
    <div class="row">
    <div class="soso col-xs-8">
      <ul>
        <li><a href="http://github.com/jaredeinstein">gits</a></li>
        <li><a href="http://twitter.com/jaredeinstein">twits</a></li>
      </ul>
    </div>
    <div class="copyright col-xs-4">
      <p>© 2015 Jerry Goldshine</p>
    </div>
  </div>
  </div>
</div>  
</body>
</html>

app/views/pages/about.html.erb
<div class="main about">
    <div class="container">
      <div class="row">
        <div class="col-md-6 thumbnail">
          <img alt="me" src="https://upload.wikimedia.org/wikipedia/en/2/2f/Jerry_Mouse.png">
        </div>
        <div class="col-md-6">
          <h2>me name <span class="highlight">jerry</span></h2>
          <p>me do things</p>
          <p>you pay me</p>
        </div>
      </div>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="main contact">
  <div class="container">
    <h2>contact me</h2>
    <div class="row">
      <div class="col-md-2"><a class="gits" href="#">gits</a></div>
      <div class="col-md-2"><a class="twits" href="#">twits</a></div>
  </div>
  </div>
</div>  

app/views/pages/portfolio.html.erb
<div class="main portfolio">
  <div class="slideshow-container">
  <div class="jumbotron slideshow">
      <ul>
        <li class="slide"><img src="http://orig08.deviantart.net/6f75/f/2009/280/6/7/portofolio_layout_by_mst4gfx.png"></li>
        <li class="slide"><img src="http://www.lifeclever.com/wp-content/uploads/2007/04/portfolio_3.jpg"></li>
        <li class="slide"><img src="http://trisakumon.files.wordpress.com/2010/12/kotak-obat.jpg"></li>
      </ul>
    </div>
  </div>
<div class="container">
  <div class="row">
    <a class="col-md-6 project" href=#>
      <div class="thumbnail-header">
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
      </div>
      <div class="thumbnail">
        <img alt="p1" src="http://orig08.deviantart.net/6f75/f/2009/280/6/7/portofolio_layout_by_mst4gfx.png">
      </div>
      <h3>p1 thingy</h3>
      <p>Thing and thing thingy</p>
    </a>
    <a class="col-md-6 project" href=#>
      <div class="thumbnail-header">
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
      </div>
      <div class="thumbnail">
        <img alt="p2" src="http://orig08.deviantart.net/6f75/f/2009/280/6/7/portofolio_layout_by_mst4gfx.png">
      </div>
      <h3>p2 thingy</h3>
      <p>Thing and thing thingy</p>
    </a>
  </div>
  <div class="row">
    <a class="col-md-6 project" href=#>
      <div class="thumbnail-header">
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
      </div>
      <div class="thumbnail">
        <img alt="p3" src="http://orig08.deviantart.net/6f75/f/2009/280/6/7/portofolio_layout_by_mst4gfx.png">
      </div>
      <h3>p3 thingy</h3>
      <p>Thing and thing thingy</p>
    </a>
    <a class="col-md-6 project" href=#>
      <div class="thumbnail-header">
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
        <div class="thumbnail-header-btn"></div>
      </div>
      <div class="thumbnail">
        <img alt="p4" src="http://orig08.deviantart.net/6f75/f/2009/280/6/7/portofolio_layout_by_mst4gfx.png">
      </div>
      <h3>p4 thingy</h3>
      <p>Thing and thing thingy</p>
    </a>
  </div>
</div>
         
</div>

app/views/pages/welcome.html.erb
<div class="main home">
  <div class="jumbotron">
    <div class="container">
      <h2>me name <span class="highlight">jerry</span>. me like pictures.</h2>
      <%= link_to "me work", portfolio_path, class: "btn right" %>
    </div>
  </div>
</div>